export const ADD_ARCH_SUCCESS = "ADD_ARCH_SUCCESS";
export const GET_ARHCS_SUCCESS = "GET_ARCHS_SUCCESS";
export const REMOVE_ARCHS_SUCCESS = "REMOVE_ARCHS_SUCCESS";
export const GET_ARCH_PRIORITIES_SUCCESS = "GET_ARCH_PRIORITIES_SUCCESS";
