export const ADD_BROWSER_PANEL_SUCCESS = "ADD_BROWSER_PANEL_SUCCESS";
export const GET_BROWSER_PANELS_SUCCESS = "GET_BROWSER_PANELS_SUCCESS";
export const REMOVE_BROWSER_PANELS_SUCCESS = "REMOVE_BROWSER_PANELS_SUCCESS";
