export const ADD_BROWSER_SUCCESS = "ADD_BROWSER_SUCCESS";
export const GET_BROWSERS_SUCCESS = "GET_BROWSERS_SUCCESS";
export const REMOVE_BROWSERS_SUCCESS = "REMOVE_BROWSERS_SUCCESS";
export const GET_BROWSER_PRIORITIES_SUCCESS = "GET_BROWSER_PRIORITIES_SUCCESS";
export const SET_BROWSER_PRIORITY_SUCCESS = 'SET_BROWSER_PRIORITY_SUCCESS'
