export const ADD_BROWSER_VERSION_SUCCESS = "ADD_BROWSER_VERSION_SUCCESS";
export const GET_BROWSER_VERSIONS_SUCCESS = "GET_BROWSER_VERSIONS_SUCCESS";
export const REMOVE_BROWSER_VERSIONS_SUCCESS = "REMOVE_BROWSER_VERSIONS_SUCCESS";
export const GET_BROWSER_VERSION_PRIORITIES_SUCCESS = "GET_BROWSER_VERSION_PRIORITIES_SUCCESS";
export const SET_BROWSER_VERSION_PRIORITY_SUCCESS = 'SET_BROWSER_VERSION_PRIORITY_SUCCESS'
