export const GET_ALL_DEVICES_SUCCESS = "GET_ALL_DEVICES_SUCCESS";
export const ADD_DEVICE_SUCCEES = "ADD_DEVICE_SUCCESS";
export const REMOVE_DEVICES_SUCCESS = "REMOVE_DEVICES_SUCCESS";
export const GET_DEVICE_PRIORITIES_SUCCESS = "GET_DEVICE_PRIORITIES_SUCCESS";
export const SET_DEVICE_PRIORITIES_SUCCESS = "SET_DEVICE_PRIORITIES_SUCCESS";
