export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const GET_ALL_FAVORITES_SUCCESS = "GET_ALL_FAVORITES_SUCCESS";
export const REMOVE_FAVORITES_URL = "REMOVE_FAVORITES_URL";
export const GET_FAVORITE_PRIORITIES_SUCCESS =
  "GET_FAVORITE_PRIORITIES_SUCCESS";
export const SET_FAVORITE_PRIORITIES_SUCCESS =
  "SET_FAVORITE_PRIORITIES_SUCCESS";
