export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const GET_ALL_FAVORITES_SUCCESS = "GET_ALL_FAVORITES_SUCCESS";
export const REMOVE_FAVORITES_SUCCESS = "REMOVE_FAVORITES_SUCCESS";
export const GET_FAVORITE_PRIORITIES_SUCCESS =
  "GET_FAVORITE_PRIORITIES_SUCCESS";
export const SET_FAVORITE_PRIORITIES_SUCCESS =
  "SET_FAVORITE_PRIORITIES_SUCCESS";
export const ADD_DOMAINS_SUCCESS = "ADD_DOMAINS_SUCCESS";
export const GET_ALL_DOMAINS_SUCCESS = "GET_ALL_DOMAINS_SUCCESS";
export const REMOVE_DOMAINS_SUCCESS = "REMOVE_DOMAINS_SUCCESS";
