export const ADD_MODEL_SUCCESS = "ADD_MODEL_SUCCESS";
export const GET_ALL_MODEL_SUCCESS = "GET_ALL_MODEL_SUCCESS";
export const REMOVE_MODELS_SUCCESS = "REMOVE_MODELS_SUCCESS";
export const GET_MODEL_PRIORITIES_SUCCESS = "GET_MODEL_PRIORITIES_SUCCESS";
