export const ADD_OS_PANEL_SUCCESS = "ADD_OS_PANEL_SUCCESS";
export const GET_OS_PANELS_SUCCESS = "GET_OS_PANELS_SUCCESS";
export const REMOVE_OS_PANELS_SUCCESS = "REMOVE_OS_PANELS_SUCCESS";
export const GET_OS_PANEL_PRIORITIES_SUCCESS = "GET_OS_PANEL_PRIORITIES_SUCCESS";
