export const ADD_OS_VERSION_SUCCESS = "ADD_OS_VERSION_SUCCESS";
export const GET_OS_VERSIONS_SUCCESS = "GET_OS_VERSIONS_SUCCESS";
export const REMOVE_OS_VERSIONS_SUCCESS = "REMOVE_OS_VERSIONS_SUCCESS";
export const GET_OS_VERSION_PRIORITIES_SUCCESS =
  "GET_OS_VERSION_PRIORITIES_SUCCESS";
