export const ADD_OS_SUCCESS = "ADD_OS_SUCCESS";
export const GET_OSES_SUCCESS = "GET_OSES_SUCCESS";
export const REMOVE_OSES_SUCCESS = "REMOVE_OSES_SUCCESS";
export const GET_OS_PRIORITIES_SUCCESS = "GET_OS_PRIORITIES_SUCCESS";
export const SET_OS_PRIORITY_SUCCESS = 'SET_OS_PRIORITY_SUCCESS'
