export const ADD_SCREEN_SUCCESS = "ADD_SCREEN_SUCCESS";
export const GET_SCREENS_SUCCESS = "GET_SCREENS_SUCCESS";
export const REMOVE_SCREENS_SUCCESS = "REMOVE_SCREENS_SUCCESS";
export const GET_SCREEN_PRIORITIES_SUCCESS = 'GET_SCREEN_PRIORITIES_SUCCESS'
export const SET_SCREEN_PRIORITY_SUCCESS = 'SET_SCREEN_PRIORITY_SUCCESS'
