export const ADD_SEARCH_ENGINES_SUCCESS = "ADD_SEARCH_ENGINES_SUCCESS";
export const GET_ALL_SEARCH_ENGINES_SUCCESS = "GET_ALL_SEARCH_ENGINES_SUCCESS";
export const REMOVE_SEARCH_ENGINES_SUCCESS = "REMOVE_SEARCH_ENGINES_SUCCESS";
export const GET_SEARCH_ENGINE_PRIORITIES_SUCCESS =
  "GET_SEARCH_ENGINE_PRIORITIES_SUCCESS";
export const SET_SEARCH_ENGINE_PRIORITIES_SUCCESS =
  "SET_SEARCH_ENGINE_PRIORITIES_SUCCESS";
