export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const REMOVE_TEMPLATES_SUCCESS = "REMOVE_TEMPLATES_SUCCESS";
export const GET_TEMPLATE_PRIORITIES_SUCCESS = "GET_TEMPLATE_PRIORITIES_SUCCESS";
export const SET_TEMPLATE_PRIORITY_SUCCESS = "SET_TEMPLATE_PRIORITY_SUCCESS";
